// <auto-generated />
using System;
using ApiCuentaAhorros.BaseDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiCuentaAhorros.Migraciones
{
    [DbContext(typeof(ContextoBaseDatos))]
    partial class ContextoBaseDatosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ApiCuentaAhorros.Entidades.SimulacionEntidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DepositoInicial")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InteresTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlazoAnios")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TasaInteresAnual")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Simulaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
